### ISSUE TITLE
Connection timeout for SessionInfo

### ISSUE THREAD

**Issue by flipback** [nimbuscontrols/EIPScanner#21]
**Is your feature request related to a problem? Please describe.**

The current implementation doesn't have timeout for TCP\IP connection. It causes very long dealys if the IP address is not available. 

**Describe the solution you'd like**

Implement connection timeout like this: http://developerweb.net/viewtopic.php?id=3196

**Comment by LouKordos** [comment]
Is this timeout also respected when sending data? Does not look like it from inspecting the code, so is it only for the initial connection? How can I specify that I want to only wait for say 100ms before I get an error instead of hanging on the receive call?
