### ISSUE TITLE
Client/Scanner Application - Question

### ISSUE THREAD

**Issue by sergio-vedois** [nimbuscontrols/EIPScanner#28]
Hi,

I need to write an application (client/scanner) that establishes a communication with an ETHERNET/IP adapter/server using both explicit and implicit(I/O) messaging.
The adapter will be coded in C/C++ using EIPStackGroup/OpENer library.

So, my questions are:
Is This library meant for that ?
Which is the max polling rate ?

I Thank in advance for the answers.

Sérgio

**Comment by jadamroth** [comment]
Hi Sergio,

1) Yes, this library is meant to enable an application to be an EtherNet/IP scanner. We've done quite a bit of testing using explicit messaging, not as much with implicit messaging. But you can find a basic example here where we tested implicit messaging connections with a Powerflex 525: https://github.com/nimbuscontrols/EIPScanner/blob/master/examples/ImplicitMessagingExample.cpp
2) Poll rate limitations are dependent more so upon both the scanner development and max adapter connections, but we poll some devices at 250ms using explicit messaging without problems

**Comment by sergio-vedois** [comment]
Thank you for the quick answer.
I will start some tests.
