### ISSUE TITLE
Access the tags in PLC by the name

### ISSUE THREAD

**Issue by abonent312** [nimbuscontrols/EIPScanner#29]
Hi, thank you for the project! I successfully built it for OpenWRT with Linaro toolchain (with backport to Cpp11) and it works perfectly.

But I need additional functionality - to read the tags (I/O) from Rockwell PLC (by CIP).
Do something like:
messageRouter.readTag(si, "arrayTag[0]")

(like it's implemented here: https://github.com/cmseaton42/node-ethernet-ip)  

I'm completely newbie in EthernetIP and CIP but I can develop (and contribute to the project) 
if you point me the right manual - how to encapsulate CIP request into Ethernet/IP frame and get the answer.
Thank you!

**Comment by jadamroth** [comment]
Hi @abonent312 

Thanks for reaching out. 

Feel free to use the project as you'd like, and we will happily accept contributions via pull requests. However, this library is intended to focus on communication to EtherNet/IP end devices, such as VFDs

Check out this library as it sounds a little more suited to what you're looking for - https://github.com/libplctag/libplctag

**Comment by abonent312** [comment]
many thanks for the hint!
