### ISSUE TITLE
Question about parameters.o2tRealTimeFormat

### ISSUE THREAD

**Issue by gpenzo** [nimbuscontrols/EIPScanner#35]
Hello
I am using your library and it works perfect.
I am just wondering what parameters.o2tRealTimeFormat is for.
I have a plc that only works if I put that variable to false. So no header will be send.
But I want to understand what it is for.

Regards Grayson.

**Comment by jadamroth** [comment]
Hi Grayson,

o2tRealTimeFormat is only for implicit messaging connections and used to format and interpret data. The O stands for originator (mostly like the application which embeds this library) and the T stands for target (I'd assume the PLC you're connecting to). You can sometimes find this setting in the Connection Manager section of your EDS file.

Please see the attached link on page 9, section 2.4.6, and it explains more in detail about EtherNet/IP realtime formats - https://www.port.de/fileadmin/user_upload/port-automation/ARDUINO/0410_060_GOAL_2_20_0_LP_ETHERNET_IP.pdf

**Comment by gpenzo** [comment]
You driver is working perfect for the last months in our robot. Thanks.
