### ISSUE TITLE
Implicit messaging rate

### ISSUE THREAD

**Issue by JoeyR** [nimbuscontrols/EIPScanner#37]
Hello,

I have your implicit messaging example working for my device (ConveyLinx-ERSC) and outputting the correct assembly. I am receiving a message on 1 second intervals and I am wondering if it's possible to decrease that interval to 100ms or faster. 

I also wanted to thank you for creating this library!

Thank you,
Joey

**Comment by JoeyR** [comment]
The way to change the interval is quite easy:

parameters.o2tRPI = 100000; // microseconds
parameters.t2oRPI = 100000; // microseconds

**Comment by jadamroth** [comment]
Glad you figured it out Joey. Thanks again for using the library, and please reach out if you have any other questions/issues

I would like to ask a favor:
Someone a couple days ago posted an issue #36 and is having troubles getting implicit messaging up and running with a UR robot. I believe they are new to the protocol and implicit isn't the easiest thing to dive into. I tried to give them some guidance, but if you wouldn't mind, could you post any non-proprietary code of your implicit ConnectionParameters example and the eds (either via pull request or directly in the issue) to give them a working example of what you've done to help them out? 

I'd appreciate it.
