### ISSUE TITLE
Inactivity timer/Consuming connections

### ISSUE THREAD

**Issue by JoeyR** [nimbuscontrols/EIPScanner#38]
Hello,

I am experiencing a 10 second timeout in the implicit messaging example. I am able to connect to my device (ConveyLinx-ERSC) and read the assembly. I found #35, which led me to the document that states: 

> Inactivity/Watchdog Timer
> This timer is is used for consuming connections. The timer is loaded with the API of the
> Originator-To-Target direction multiplied by the Connection Timeout Multiplier. The timer
> is reset whenever valid connection data was consumed. If the timer expires the connection is
> considered timed out and will be closed. For the first reception the timer is set to at least 10
> seconds.

I'm wondering what I need to do to "consume" the connection or even extend the inactivity timer. I am trying to set up a service that is always monitoring certain bits in the assembly. One option that I have right now is to accept the inactivity timer and set up a new connection, but then I need to somehow listen for the disconnect.  Hope that makes sense!

Thank you,
Joey

**Comment by jadamroth** [comment]
Yes, your issue makes sense. I agree that we should add a disconnect callback as a feature to the library. However, I don't think recreating a connection each time there's a disconnect is a great solution. This should be handled more as a keep alive method. I think the best solution is as stated in your pasted paragraph:
```
 The timer is reset whenever valid connection data was consumed.
```

We've tested explicit messaging significantly more than implicit, so I can't verify implicits current stability. Will you please attached your code and how you're handling, so I can take a look?

**Comment by JoeyR** [comment]
This sets up the handler just like in your example, but instead of counting down to zero when calling handleConnections I just do it forever.

Here's my implicit messaging code:

```
void eip::connect_to_conveylinx() {
  auto si = std::make_shared<eipsi>("192.168.202.21", 0xAF12,
                                    std::chrono::milliseconds(200));

  // Implicit messaging
  ConnectionManager connectionManager;

  ConnectionParameters parameters;
  parameters.connectionPath = {
      0x20, 0x04, 0x25, 0x00, 0x01, 0x00, 0x2D, 0x00,
      0x34, 0x01, 0x2D, 0x00, 0x33, 0x01};  // PLCIO with Reset Protection
                                            

  parameters.o2tRealTimeFormat = true;

  parameters.t2oNetworkConnectionParams |= NetworkConnectionParams::P2P;
  parameters.t2oNetworkConnectionParams |=
      NetworkConnectionParams::SCHEDULED_PRIORITY;

  parameters.t2oNetworkConnectionParams |= 46; // Assem 307
  parameters.o2tNetworkConnectionParams |= NetworkConnectionParams::P2P;
  parameters.o2tNetworkConnectionParams |=
      NetworkConnectionParams::SCHEDULED_PRIORITY;
  parameters.o2tNetworkConnectionParams |= 54; // Assem 308

  parameters.connectionTimeoutMultiplier = 4;

  parameters.o2tRPI = 50000;
  parameters.t2oRPI = 50000;

  parameters.transportTypeTrigger |= NetworkConnectionParams::CLASS1;

  auto io = connectionManager.forwardOpen(si, parameters);

  if (auto ptr = io.lock()) {
    ptr->setDataToSend(std::vector<uint8_t>(54));

    ptr->setReceiveDataListener(
        [](auto realTimeHeader, auto sequence, auto data) {
          std::ostringstream ss;
          ss << "secNum=" << sequence << " data=";
          for (auto& byte : data) {
            ss << "[" << std::hex << (int)byte << "]";
          }

          std::cout << "Received: " << ss.str() << std::endl;
        });

    ptr->setCloseListener([]() { std::cout << "Closed"; });
  }

  while (true) {
    connectionManager.handleConnections(std::chrono::milliseconds(10));
  }

  // connectionManager.forwardClose(si, io);
}
```

I am interested in explicit messaging but I don't quite understand the EPath yet (I don't see "ClassId, InstanceId, AttributeId" in my eds file). I also don't think my devices can handle the Parameter Object example so it makes it more difficult to figure that out.

Thank you,
Joey

**Comment by jadamroth** [comment]
For explicit messaging, run this example to get your parameters as the parameters are not in the EDS file. Let me know if you need more help with this (however, if you're controlling an adapter, implicit is a much better choice) - https://github.com/nimbuscontrols/EIPScanner/blob/master/examples/ParameterObjectExample.cpp

For your issue with implicit, do you receive an error, exception, message, or anything for the timeout or does it just disconnect and exit the program? Can you explain in a little more detail about what happens? Also, is the timeout always 10 seconds even if you change some of the parameters?

**Comment by JoeyR** [comment]
The explicit code never returns because of the busy wait handleConnection. Here's my output for implicit:
``` 
...
Received: secNum=198 data=[0][0][0][80][2][0][c0][5d][0][0][0][0][1f][21][0][8][0][0][0][0][20][21][0][8][0][0][0][0][6][6][6][6][0][0][0][0][9d][1][0][0][0][0][0][0][0][0]
Received: secNum=199 data=[0][0][0][80][2][0][c0][5d][0][0][0][0][1f][21][0][8][0][0][0][0][20][21][0][8][0][0][0][0][6][6][6][6][0][0][0][0][9d][1][0][0][0][0][0][0][0][0]
Received: secNum=200 data=[0][0][0][80][2][0][c0][5d][0][0][0][0][1f][21][0][8][0][0][0][0][20][21][0][8][0][0][0][0][6][6][6][6][0][0][0][0][9d][1][0][0][0][0][0][0][0][0]
[WARNING] Connection SeriaNumber=1 is closed by timeout
```



I would like to get implicit working but I'm just not sure how to read my eds file: [conveylinx.txt](https://github.com/nimbuscontrols/EIPScanner/files/5717476/conveylinx.txt)

I can do Epath(1,1,1) and get the vendor ID.

As far as I can tell,  "EPath(ParameterObject::CLASS_ID, 0, MAX_INSTANCE)" in the example does not work for my device. I am able to get some form of output of "3" by changing the EPath to "EPath(0xF6, 0, 3)" but it's unclear to me what it's returning. The max instance is 3 (from "Ethernet Link Class" with object class code 0xF6)

Thanks,
Joey
