### ISSUE TITLE
I am unable to find this package with cmake 'find_package(EIPScanner REQUIRED)`.

### ISSUE THREAD

**Issue by amussell** [nimbuscontrols/EIPScanner#40]
I am writing an EIP Scanner for the bluebotics ANT lite+. My CMake project needs to depend on this library, but I can't figure out how to set that up. Why can I not find the package after building and installing it?

**Comment by jadamroth** [comment]
I don't completely understand what you're asking or what you're trying to do - more info would be helpful. However, the linked libraries should output in cmake-build-path/src/ then you link and include them from there. 

Did you try the working examples?

**Comment by amussell** [comment]
I was able to figure this out. I needed to use find_library rather than find_package as this repo is configured to work as a library than a package (because no CMake config is generated on install).
