### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by jadamroth** [nimbuscontrols/EIPScanner#41]
Will someone with a windows computer test one of the examples from this fork #39 by @luntik2012 compiling with mingw, so I can merge this pull request and create release 1.1.0 that allows for windows support?

Thanks

**Comment by luntik2012** [comment]
I've tested only `SessionInfo` and `MessageRouter` objects creation, `GET_ATTRIBUTE_SINGLE` and `SET_ATTRIBUTE_SINGLE` requests.

**Comment by jadamroth** [comment]
Closed with #39 

Create new issues and pull requests from any problems with these commits
