### ISSUE TITLE
Make Html Documentation Fails

### ISSUE THREAD

**Issue by jallard-sr** [nimbuscontrols/EIPScanner#53]
**Describe the bug**
Running `make html` in the docs directory fails for lack of a sphinx_rtd_theme file.

**To Reproduce**
Run `make html` in the docs directory.

Example:
```
jallard@jallard-VB20:~/work/EIPScanner/docs$ make html
Running Sphinx v1.8.5

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/lib/python3/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/jallard/work/EIPScanner/docs/source/conf.py", line 19, in <module>
    import sphinx_rtd_theme
ModuleNotFoundError: No module named 'sphinx_rtd_theme'

make: *** [Makefile:19: html] Error 2
```

**Expected behavior**
I was hoping for some nicely formatted documentation.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Compiler: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, python3-sphinx 1.8.5-7ubuntu3 
 - Version: Tried in master (commit a7e88cfc4c44585e64512973e1fd54fc7a6d606f) and the tag 1.2.0

**Comment by jadamroth** [comment]
Please try running
```sh
pip install sphinx_rtd_theme
```

**Comment by jallard-sr** [comment]
Thanks for the suggestion, I just ran `pip3 install -r requirements.txt`, and now `make html` works. So perhaps this ticket should instead be about needing clues for the Python clueless in the README.md file.

**Comment by jallard-sr** [comment]
Closing the bug, the feature worked once I knew how to install its dependencies. I'm glad I took the time to get the documentation formatted, it looks great and is very informative.

**Comment by jadamroth** [comment]
There's also a web based documentation at this link - https://eipscanner.readthedocs.io/en/latest/

**Comment by jallard-sr** [comment]
Thanks!
