### ISSUE TITLE
Get error string of product name

### ISSUE THREAD

**Issue by singlebear** [nimbuscontrols/EIPScanner#54]
![image](https://user-images.githubusercontent.com/48552037/122373895-73cf3180-cf94-11eb-8628-76b83f86d60c.png)
![image](https://user-images.githubusercontent.com/48552037/122377867-09b88b80-cf98-11eb-8832-573cae389796.png)
![image](https://user-images.githubusercontent.com/48552037/122377908-1341f380-cf98-11eb-8326-1ef6f1fc055e.png)

CipBaseString
```

		std::string toStdString() const {
			char *buffer= new char[_length];
			std::memcpy(buffer, _data.data(), _length);
			std::string temp(buffer);
			delete buffer;
			return temp;
		}
```
The reason is std::memcpy。
Change code like this can fix this problem.
```

		std::string toStdString() const {
			char *buffer= new char[_length];
			std::memcpy(buffer, _data.data(), _length);
			std::string temp(buffer,_length);
			delete buffer;
			return temp;
		}
```

**Comment by jadamroth** [comment]
Thanks. I will update this on next release

**Comment by jadamroth** [comment]
Sorry, I should have actually read the code before commenting. 

What is the point of creating a buffer with a raw pointer? I do not like this solution

**Comment by singlebear** [comment]
> Sorry, I should have actually read the code before commenting.
> 
> What is the point of creating a buffer with a raw pointer? I do not like this solution

Sorry，I'm not a native English speaker.I can't see your meaning clearly.What you mean is there is  a better way to  convert 'std::vector<uint8>' to 'string' ?

The only difference that i change is [std::string temp(buffer);] to [std::string temp(buffer,_length);]. Because it will find the last '\0' when construct string with char*.And If the length is not specified,it may out the memory of right space.The string may be too short or too long.

**Comment by jadamroth** [comment]
We should not need to allocate new memory with a raw pointer to fix this

My EIP device does not provide the same issue, so I'm not able to replicate your error

I am flexible with the solution to fix this issue, but it should require allocating new memory

**Comment by singlebear** [comment]
> We should not need to allocate new memory with a raw pointer to fix this
> 
> My EIP device does not provide the same issue, so I'm not able to replicate your error
> 
> I am flexible with the solution to fix this issue, but it should require allocating new memory

Could this be a compiler problem?I build it with MSVC2017 + win10.
By the way,This needs a little modification when build by MSVC .MSVC don`t support the grammar of struct that 'designated initializer'( IOS C99).

```
struct timeval tv = {

#ifdef __APPLE__
		.tv_sec = static_cast<__darwin_suseconds_t>(recvTimeout.count()/1000),
		.tv_usec =  static_cast<__darwin_suseconds_t>((recvTimeout.count()%1000)*1000)
#elif __unix__
		.tv_sec = static_cast<__time_t>(recvTimeout.count()/1000),
		.tv_usec =  static_cast<__time_t>((recvTimeout.count()%1000)*1000)
#elif defined(_WIN32) || defined(WIN32) || defined(_WIN64)
		.tv_sec = static_cast<long int>(recvTimeout.count()/1000),
		.tv_usec =  static_cast<long int>((recvTimeout.count()%1000)*1000)
#endif

};
```
Code like this will not compile on MSVC.You can add compilation platform macros for Windows to solve this situation.
This is my modification.Not use '  timeval tv{ static_cast<long int>(recvTimeout.count()/1000), static_cast<long int>((recvTimeout.count()%1000)*1000)}' Because it may assign the wrong value when the structure variable definition order changes.
```
#ifdef _MSVC
 timeval tv;
 tv.tv_sec = static_cast<long int>(recvTimeout.count()/1000),
 tv.tv_usec =  static_cast<long int>((recvTimeout.count()%1000)*1000)
#else
struct timeval tv = {
#ifdef __APPLE__
		.tv_sec = static_cast<__darwin_suseconds_t>(recvTimeout.count()/1000),
		.tv_usec =  static_cast<__darwin_suseconds_t>((recvTimeout.count()%1000)*1000)
#elif __unix__
		.tv_sec = static_cast<__time_t>(recvTimeout.count()/1000),
		.tv_usec =  static_cast<__time_t>((recvTimeout.count()%1000)*1000)
#elif defined(_WIN32) || defined(WIN32) || defined(_WIN64)
		.tv_sec = static_cast<long int>(recvTimeout.count()/1000),
		.tv_usec =  static_cast<long int>((recvTimeout.count()%1000)*1000)
#endif
#endif
};
```

**Comment by jadamroth** [comment]
I don't have a Windows computer to test this, but the code looks fine to me

However, I don't see how this code could interfere with the product name string
