### ISSUE TITLE
Need more  instructions  about struct "ConnectionParameters "

### ISSUE THREAD

**Issue by singlebear** [nimbuscontrols/EIPScanner#55]
I would like to learn more about parameter setting instructions of struct "ConnectionParameters ". What is the meaning of each parameter and how to set it correctly.

The query history issues found some issues related to implicit messages that are partially mentioned.But it's not very detailed, especially the “ConnectionParameters::connectionPath” parameter that bothers me.

  Thanks !

**Comment by jadamroth** [comment]
The connection path is dependent on your EDS file

Begin by downloading the EDS file from your end device using the fileobject example

There's a few examples in the repo from people who have successfully connected with implicit message along with their EDS file. I'd recommend you to reference the Yaskawa mp3300iec issue and example as it's very in depth

**Comment by singlebear** [comment]
> The connection path is dependent on your EDS file
> 
> Begin by downloading the EDS file from your end device using the fileobject example
> 
> There's a few examples in the repo from people who have successfully connected with implicit message along with their EDS file. I'd recommend you to reference the Yaskawa mp3300iec issue and example as it's very in depth

I used to read the issuue of 'Yaskawa' carefully,and compare and read the EDS file with the set address.But i still can get the link of EDS file path with ConnectionParameters::connectionPath .
The first three numbers are the same, but the last three of each Assem are not.
And the author ended up using explicit messages instead of implicit ones.

**Comment by jadamroth** [comment]
Sorry, but I don't completely understand your message
