### ISSUE TITLE
Executable file is not created

### ISSUE THREAD

**Issue by Gaetanos-99** [nimbuscontrols/EIPScanner#67]
Hi, 

I installed EIPScanner. Now I'm trying to run the example cited [here](https://eipscanner.readthedocs.io/en/latest/getting_started.html#) on my Raspberry Pi 3. After running "cmake .." I don't see no executable files. So, I cannot run "./hi_eip". Any help would be highly welcome! Thank you very much in advance.
PS: I am quite new to using CMake.

**EDIT**:
The command in order to build the CMake files "cmake --build ." was missing. I could manage to create the executable file. But now I have the error: "error while loading shared libraries: libEIPScanner.so.1: cannot open shred object file: No such file or directory". Any idea how I can solve this?

Kindly regards
Gaetan

**Comment by Gaetanos-99** [comment]
**EDIT**

The command in order to build the CMake files "cmake --build ." was missing. I could manage to create the executable file. But now I have the error: "error while loading shared libraries: libEIPScanner.so.1: cannot open shred object file: No such file or directory". Any idea how I can solve this?

**Comment by aaronrenny** [comment]
Hi,

I am also facing the similar problem of not getting an excecutable file. Can you please tell me how you managed to solve the problem. Any kind of help would be appreciated.

Regards,
Aaron

**Comment by 8188** [comment]
same problem. 
`sudo /sbin/ldconfig -v` may solve it.
