### ISSUE TITLE
EIP scanner with am64x evm

### ISSUE THREAD

**Issue by aaronrenny** [nimbuscontrols/EIPScanner#68]
Hi all,

I am currently working on a project that involves the usage of am64x evm as an ethernet/ip adapter. In order to test out this functionality, I have been looking for ethernet/ip scanner (master) running on PC. Can anyone tell me if the EIP Scanner will serve this purpose?

I am planning to use my laptop (running EIP scanner) as the ethernet/ip master and am64x as ethernet/ip slave. Can anyone tell me if this is possible. I am new to this field , any type of help will be appreciated.

Thank you.

**Comment by jadamroth** [comment]
Yes, this library will work as a scanner on your PC
