### ISSUE TITLE
EIPScanner for an Adapter?

### ISSUE THREAD

**Issue by franreal** [nimbuscontrols/EIPScanner#94]
I hope this question is not as silly as it sounds: Can the EIPScanner library be used to write the code for an Ethernet/IP Adapter?

As a Scanner can do everything an Adapter does (and more!), it makes sense we could use this library to code an Adapter, right?

If so, which is the way to go? Is there any example in this library that is almost an Adapter with the typical input/output/config assembly object configuration? The Implicit Messaging example? The Yaskawa code?

Thanks!

**Comment by tpcorrea** [comment]
Hi, @franreal.

First a disclaimer, I am no expert in EIP and have not deep knowledge on the EIPScanner. Thats said, I would say EIPScanner is not the best starting point for implementing an Adapter. As the roles are inverted, you won't have support inside the library for simple things, like receiving a TCP packet to open the explicit message channel. 

I guess you will better served with OpENer (https://github.com/EIPStackGroup/OpENer) instead. 
KR,
Tomas

**Comment by franreal** [comment]
Gracias @tpcorrea,

OpENer is in fact great, and you can still use EIPScanner to test your Adapter.
The implicit messaging examples work right out of the box! 
For me, more than enough to close the issue.

Thanks!
Fran
